import { routes } from './routes'
import type { PortalNavItem } from '@nexus/config'

/** Extended developer portal navigation — website-owned platform features. */
export const developerPlatformNav: PortalNavItem[] = [
  { label: 'Beta Program', path: routes.developerPortalBeta.path },
  { label: 'Invitations', path: routes.developerPortalInvitations.path },
  { label: 'Feedback', path: routes.developerPortalFeedback.path },
  { label: 'Bug Reports', path: routes.developerPortalBugReport.path },
  { label: 'Crash Analytics', path: routes.developerPortalCrashes.path },
  { label: 'SDK Wizard', path: routes.developerPortalSdkWizard.path },
  { label: 'Tutorials', path: routes.developerPortalTutorials.path },
  { label: 'API Explorer', path: routes.developerPortalApiExplorer.path },
  { label: 'AI Assistant', path: routes.developerPortalAiAssistant.path },
  { label: 'Code Generator', path: routes.developerPortalCodeGenerator.path },
  { label: 'Example Library', path: routes.developerPortalExamples.path },
  { label: 'Certification', path: routes.developerPortalCertification.path },
  { label: 'Reputation', path: routes.developerPortalReputation.path },
  { label: 'SDK Explorer', path: routes.developerPortalSdkExplorer.path },
  { label: 'Playground', path: routes.developerPortalPlayground.path },
  { label: 'Applications', path: routes.developerPortalApplications.path },
  { label: 'Organizations', path: routes.developerPortalOrganizations.path },
  { label: 'Robot Registry', path: routes.developerPortalRobotRegistry.path },
  { label: 'Behavior Library', path: routes.developerPortalBehaviors.path },
  { label: 'Simulation Jobs', path: routes.developerPortalSimulation.path },
  { label: 'Marketplace Uploads', path: routes.developerPortalMarketplaceUploads.path },
  { label: 'Release History', path: routes.developerPortalReleaseHistory.path },
  { label: 'Developer Analytics', path: routes.developerPortalAnalytics.path },
  { label: 'Billing', path: routes.developerPortalBilling.path },
  { label: 'Payouts', path: routes.developerPortalPayouts.path },
  { label: 'Activity', path: routes.developerPortalActivity.path },
]

export const developerPlatformSections = [
  {
    id: 'beta',
    title: 'Beta Program',
    description: 'Dashboard, applications, feedback, bugs, and crash analytics.',
    path: routes.developerPortalBeta.path,
    status: 'beta' as const,
  },
  {
    id: 'projects',
    title: 'Projects',
    description: 'Organize SDK integrations, behaviors, and deployment targets.',
    path: routes.developerPortalProjects.path,
    status: 'beta' as const,
  },
  {
    id: 'sdk-downloads',
    title: 'SDK Downloads',
    description: 'Download NEXUS SDK packages and CLI tooling.',
    path: routes.developerPortalSdk.path,
    status: 'beta' as const,
  },
  {
    id: 'applications',
    title: 'Applications',
    description: 'Register OAuth applications and manage client credentials.',
    path: routes.developerPortalApplications.path,
    status: 'beta' as const,
  },
  {
    id: 'organizations',
    title: 'Organizations',
    description: 'Team workspaces, roles, and sandbox organizations.',
    path: routes.developerPortalOrganizations.path,
    status: 'beta' as const,
  },
  {
    id: 'robot-registry',
    title: 'Robot Registry',
    description: 'Cloud-connected robot inventory and provisioning.',
    path: routes.developerPortalRobotRegistry.path,
    status: 'beta' as const,
  },
  {
    id: 'behaviors',
    title: 'Behavior Library',
    description: 'Author, version, and publish robot behaviors.',
    path: routes.developerPortalBehaviors.path,
    status: 'beta' as const,
  },
  {
    id: 'simulation',
    title: 'Simulation Jobs',
    description: 'Validate behaviors in NEXUS simulation before deployment.',
    path: routes.developerPortalSimulation.path,
    status: 'architecture' as const,
  },
  {
    id: 'marketplace',
    title: 'Marketplace Uploads',
    description: 'Publish distributable skills and models.',
    path: routes.developerPortalMarketplaceUploads.path,
    status: 'beta' as const,
  },
  {
    id: 'releases',
    title: 'Release History',
    description: 'Audit trail of SDK and behavior releases.',
    path: routes.developerPortalReleaseHistory.path,
    status: 'beta' as const,
  },
  {
    id: 'analytics',
    title: 'Developer Analytics',
    description: 'API usage, downloads, and portal activity metrics.',
    path: routes.developerPortalAnalytics.path,
    status: 'beta' as const,
  },
  {
    id: 'api-keys',
    title: 'API Keys',
    description: 'Manage authentication keys for NEXUS cloud APIs.',
    path: routes.developerPortalApiKeys.path,
    status: 'beta' as const,
  },
] as const
